config/routes.rb
Rails.application.routes.draw do

  root 'invoices#index'

  get 'invoices' => 'invoices#index'
  get 'invoices/:id' => 'invoices#invoice_api'
  post 'invoice/ajax_create' => 'invoices#create_ajax_invoice'
  # VVVVVVV temp for Cloud Elements Setup VVVVVVV
  get 'invoice/new!' => 'invoices#temp_edit_invoice_api'

  resources :users
  resources :pos

  get '/sign-in' => 'sessions#new', as: :signin
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy', as: :signout

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :invoices

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  after_save :send_cloud_elements_webhook

  has_many :transactions, dependent: :destroy
  has_many :items, through: :transactions
  belongs_to :pos
  belongs_to :customer

  def build_invoice_hash
    invoice_hash = {}
    invoice_hash[:customer] = self.customer.name
    invoice_hash[:customer_id] = self.customer.id
    invoice_hash[:card_type] = self.customer.cc_type
    invoice_hash[:card_last4_digits] = self.customer.cc_last4
    invoice_hash[:authorization_code] = self.customer.cc_auth
    invoice_hash[:quickbooks_id] = "1|0"
    invoice_hash[:xero_id] = "bfb38ca8-a0fc-4f37-b48b-d46c303702ac"
    invoice_hash[:greatplains_id] = "100"
    invoice_hash[:freshbooks_id] = "293802"
    invoice_hash[:netsuite_id] = "7250"
    invoice_hash[:posable_invoice_id] = self.id + 1000
    transactions = self.transactions
    invoice_hash[:transactions] = {}
    transactions.each do |transaction|
      invoice_hash[:transactions][transaction.id] = {item_id: transaction.item.id, name: transaction.item.name, quantity: transaction.qty, unit_price: transaction.item.price}
    end
    invoice_hash[:total] = self.total
    invoice_hash[:pos_name] = self.pos.name
    invoice_hash[:date] = self.updated_at.strftime("%m/%d/%Y")
    invoice_hash[:time] = self.updated_at.strftime("%H:%M:%S")
    invoice_hash
  end

  def send_cloud_elements_webhook
    if self.total && self.total > 0
      require "http"
      response1 = HTTP.post("https://staging.cloud-elements.com/elements/api-v2/events/posable",
        :json => {:status => "ok",
                  :message => "New/Edited POS ID and Token",
                  :record_id => self.id,
                  :token => User.find_by(username: "ce").auth_token,
                  :lastUpdated => self.updated_at.strftime("%m/%d/%Y") + " " + self.updated_at.strftime("%Y-%m-%dT%H:%M:%S"),
        }
      )
      response2 = HTTP.post("https://qa.cloud-elements.com/elements/api-v2/events/posable",
        :json => {:status => "ok",
                  :message => "New/Edited POS ID and Token",
                  :record_id => self.id,
                  :token => User.find_by(username: "ce").auth_token,
                  :lastUpdated => self.updated_at.strftime("%m/%d/%Y") + " " + self.updated_at.strftime("%Y-%m-%dT%H:%M:%S"),
        }
      )
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

 has_many :transactions

end

app/models/pos.rb
class Pos < ActiveRecord::Base

  has_many :invoices

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  belongs_to :pos
  belongs_to :item

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  before_create :set_auth_token

  private
    def set_auth_token
      return if auth_token.present?
      self.auth_token = generated_auth_token
    end

    def generated_auth_token
      SecureRandom.uuid.gsub(/\-/,'')
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  def authenticate
    redirect_to root_path unless current_user
  end

  helper_method :current_user

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate, except: [:index, :temp_edit_invoice_api, :create_ajax_invoice]

  def index
    @invoices =  Invoice.all
  end

  def create_ajax_invoice
    new_invoice = Invoice.create!()
    transactions = JSON.parse(params[:transactions])
    item_total = 0
    transactions.each do |transaction|
      Transaction.create!(item_id: transaction['item_id'], qty: transaction['item_qty'], invoice_id: new_invoice.id)
      item_total += transaction['item_qty'].to_i * Item.find(transaction['item_id']).price
    end

    new_invoice.update!(total: item_total, customer_id: params['customer_id'], pos_id: params['pos_id'])

    respond_to do |format|
      format.json {render json: new_invoice}
    end
  end

  def invoice_api
    invoice = Invoice.find(params[:id])
    if invoice
      invoice_api = invoice.build_invoice_hash
      respond_to do |format|
        format.json {render json: invoice_api}
      end
    else
      respond_to do |format|
        format.json {render json: pos.errors, status: :unprocessable_entity}
      end
    end
  end

  def temp_edit_invoice_api
    new_invoice = Invoice.create!(pos_id: Pos.last.id, customer_id: Customer.last.id)
    new_transaction = Transaction.create!(invoice_id: new_invoice.id, item_id: Item.last.id, qty: 10)
    new_invoice.update!(total: Item.last.price * new_transaction.qty)
    render json: {new_invoice: new_invoice, new_transaction: new_transaction}
  end

  protected
    def authenticate
      authenticate_token || render_unauthorized
    end

    def authenticate_token
      authenticate_with_http_token do |token, options|
        User.find_by(auth_token: token)
      end
    end

    def render_unauthorized
      self.headers['WWW-Authenticate'] = 'Token realm="Application"'
      render json: 'Bad Token', status: 401
    end

end

app/controllers/pos_controller.rb
class PosController < ApplicationController

  def index
  end

  def new
    @pos = Pos.new
  end

  def create
    @pos = Pos.new(pos_params)
    if @pos.save
      redirect_to user_path(current_user), notice: 'POS successfully created'
    end
  end

  def update
    @pos = Pos.find(params[:id])
    if @pos.update(pos_params)
      redirect_to user_path(current_user), notice: 'POS successfully updated'
    end
  end

  def destroy
    @pos = Pos.find(params[:id])
    @pos.destroy
      redirect_to user_path(current_user), alert: 'POS Deleted'
  end

  private

  def pos_params
    params.require(:pos).permit(:name, :description)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:username])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_path(user), notice: "Welcome Back #{user.name}!"
      else
        @sign_in_error = "Username / Password combination is invalid"
        render :new
      end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: [:index]

  def index
  end

  def show
    @pos = Pos.new
    @all_pos = Pos.all
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: 'Account Successfully Updated'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invoices/_new_customer_modal.html.erb
<div class="modal fade" id="new-customer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Customer</h4>
      </div>
      <div class="modal-body">

        <input class='form-control' id='new_name'></input>

        <div class="modal-footer">
          <div class='btn btn-info btn-custom' id='add_customer'>Add Customer</div>
        </div>

      </div>

    </div>
  </div>
</div>

app/views/invoices/_pay_success_modal.html.erb
<div class="modal fade" id="pay-success" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body text-center">
        <p><h2>Invoice Successfully Created</h2></p>
      </div>
    </div>
  </div>
</div>

app/views/invoices/index.html.erb
<div class='well col-md-12 top-header'>
  <div class='col-md-6'><%= image_tag('POSable.png') %></div>
  <div class='col-md-offset-10 text-center'>
    <h4>POSable.io</h4>
    <h5>1215 Delaware St</h5>
    <h5>Denver, CO 80204</h5>
    <h5>303-386-8804</h5>
    <br>
    <span class='glyphicon glyphicon-cog' aria-hidden='true' id='settings'> SETTINGS</span>
  </div>
</div>

<div class="col-md-6">
  <div class="well">

    <div class='row'>
      <div class='col-md-5'><h4>Invoice #1</h4></div>
      <button type="button" class="col-md-1 btn-info btn-custom btn-md" data-toggle="modal" data-target="#new-customer">New</button>
      <div class='col-md-6'>
        <select class="form-control" id="select">
          <option selected disabled>Select Customer...</option>
          <option>David</option>
          <option>Nick</option>
        </select>
      </div>
      <%= render partial: 'invoices/new_customer_modal' %>
    </div>

    <hr class='header'>

    <div id='invoice_list'>
      <div class='row text-center'>
        <div class='col-md-1'></div>
        <div class='col-md-7'>Item</div>
        <div class='col-md-2'>Quantity</div>
        <div class='col-md-2'>Price</div>
      </div>
      <hr class='header'>
      <div class='row line_items'></div>
    </div>

    <hr class='header'>

    <div class='row'><br>
      <div class='col-md-2'><a href='#' class='btn btn-default btn-block' id='clear'>CLEAR</a></div>
      <div class='col-md-1'></div>
      <div class='col-md-2'><a href='#' class='btn btn-info btn-custom btn-block'>CASH</a></div>
      <div class='col-md-3'><button type="button" class="col-md-1 btn btn-info btn-custom btn-block" data-toggle="modal" data-target="#pay-success" id='pay'>PAY</button></div>
      <div class='col-md-4 text-left test'><h3 class='total'>Total:&nbsp;&nbsp;$<span id='total'></span></h3></div>
    </div><br>

    <%= render partial: 'invoices/pay_success_modal' %>
  </div>
</div>

<div class="col-md-6 text-center">

  <div class='col-md-6'>
    <div class="well col-md-12">
      <div><h4 id='name'>Bacon</h4></div><hr class='item_header'>
      <div class='col-md-6'><%= image_tag('bacon.png') %></div>
      <div class='col-md-6'>
        <div>$&nbsp;<span id='price'>4.99</span></div>
        <div id='2'><a href="#" class="btn btn-info btn-item">+ Add</a></div>
      </div>
    </div>

    <div class="well col-md-12">
      <div><h4 id='name'>Salami</h4></div><hr class='item_header'>
      <div class='col-md-6'><%= image_tag('salami.png') %></div>
      <div class='col-md-6'>
        <div>$&nbsp;<span id='price'>6.99</span></div>
        <div id='4'><a href="#" class="btn btn-info btn-item">+ Add</a></div>
      </div>
    </div>

    <div class="well col-md-12">
      <div><h4 id='name'>Asparagus</h4></div><hr class='item_header'>
      <div class='col-md-6'><%= image_tag('asparagus.png') %></div>
      <div class='col-md-6'>
        <div>$&nbsp;<span id='price'>5.50</span></div>
        <div id='6'><a href="#" class="btn btn-info btn-item">+ Add</a></div>
      </div>
    </div>

    <div class="well col-md-12">
      <div><h4 id='name'>Salmon</h4></div><hr class='item_header'>
      <div class='col-md-6'><%= image_tag('salmon.png') %></div>
      <div class='col-md-6'>
        <div>$&nbsp;<span id='price'>9.99</span></div>
        <div id='8'><a href="#" class="btn btn-info btn-item">+ Add</a></div>
      </div>
    </div>
  </div>

  <div class='col-md-6'>
    <div class="well col-md-12">
      <div><h4 id='name'>Cheddar</h4></div><hr class='item_header'>
      <div class='col-md-6'><%= image_tag('cheddar.png') %></div>
      <div class='col-md-6'>
        <div>$&nbsp;<span id='price'>8.99</span></div>
        <div id='3'><a href="#" class="btn btn-info btn-item">+ Add</a></div>
      </div>
    </div>

    <div class="well col-md-12">
      <div><h4 id='name'>Provolone</h4></div><hr class='item_header'>
      <div class='col-md-6'><%= image_tag('provolone.png') %></div>
      <div class='col-md-6'>
        <div>$&nbsp;<span id='price'>6.49</span></div>
        <div id='5'><a href="#" class="btn btn-info btn-item">+ Add</a></div>
      </div>
    </div>

    <div class="well col-md-12">
      <div><h4 id='name'>Broccoli</h4></div><hr class='item_header'>
      <div class='col-md-6'><%= image_tag('broccoli.png') %></div>
      <div class='col-md-6'>
        <div>$&nbsp;<span id='price'>4.99</span></div>
        <div id='7'><a href="#" class="btn btn-info btn-item">+ Add</a></div>
      </div>
    </div>

    <div class="well col-md-12">
      <div><h4 id='name'>Apples</h4></div><hr class='item_header'>
      <div class='col-md-6'><%= image_tag('apples.png') %></div>
      <div class='col-md-6'>
        <div>$&nbsp;<span id='price'>2.99</span></div>
        <div id='9'><a href="#" class="btn btn-info btn-item">+ Add</a></div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BanktecApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<div class='container'>
  <% flash.each do |type, message| %>
  <% if type == "notice" %>
  <div class='row text-center'>
    <div class="col-md-offset-3 col-md-6 alert alert-success text-center" role="alert"><%= message %></div>
  </div>
  <% elsif type == "alert" %>
  <div class='row text-center'>
    <div class="col-md-offset-3 col-md-6 alert alert-danger text-center" role="alert"><%= message %></div>
  </div>
  <% end %>
  <% end %>

  <body>

    <%= yield %>
  </body>
</div>

</html>

app/views/users/_edit_pos_modal.html.erb
<div class="modal fade" id="edit-pos-<%= pos.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit POS</h4>
      </div>
      <div class="modal-body">

        <%= form_for pos do |f| %>

        <div class="form-group">
          <%= f.label 'POS Name' %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class='form-group'>
          <%= f.label 'Description' %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>

        <div class="modal-footer">
          <%= f.submit 'Update POS', class:'btn btn-info btn-custom' %>
        </div>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/users/_edit_user_modal.html.erb
<div class="modal fade" id="edit-user-<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit Account</h4>
      </div>
      <div class="modal-body">

        <%= form_for user do |f| %>

        <div class="form-group">
          <%= f.label 'Company Name' %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="modal-footer">
          <%= f.submit class:'btn btn-info btn-custom' %>
        </div>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/users/_new_pos_modal.html.erb
<div class="modal fade" id="new-pos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New POS</h4>
      </div>
      <div class="modal-body">


        <%= form_for @pos, url: pos_path, method: :post do |f| %>

        <div class="form-group">
          <%= f.label 'POS Name' %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class='form-group'>
          <%= f.label 'Description' %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>

        <div class="modal-footer">
          <%= f.submit 'Create POS', class:'btn btn-info btn-custom' %>
        </div>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='text-center' id='home-back'>
  <%= image_tag('POSable_white.png') %>
  <div>
    <br>
    <div class='col-md-2 col-md-offset-4'>
      <%= button_to 'Demo', invoices_path, class:'btn btn-block btn-item btn-info login_button', method: :get %>
    </div>
    <div class='col-md-2'>
      <%= button_to 'Sign In', signin_path, class:'btn btn-block btn-item btn-info login_button', method: :get %>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div id='dash_header'>
  <div class='col-md-4'><%= image_tag('POSable_dash.png') %> </div>
  <div class='col-md-6'></div>
  <div class='col-md-2 account'>
    <ul class="nav nav-pills">
      <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= current_user.name %> <span class="caret"></span>
          </a>
        <ul class="dropdown-menu">
          <li><a href="#" data-toggle='modal' data-target='#edit-user-<%= current_user.id %>'>Edit Account</a></li>
          <li class="divider"></li>
          <li><a href="/users">Logout</a></li>
        </ul>
      </li>
    </ul>
    <%= render partial: 'users/edit_user_modal', locals: {user: current_user} %>
  </div>
</div>

<div><hr id='dash_line'></div>
<div><br>
    <h2>POS Terminals&nbsp;-&nbsp;</h2>
    <button type="button" class="btn-info btn-item" data-toggle="modal" data-target="#new-pos" id='#new_pos_button'>+ New</button>
  <ul class="nav nav-tabs"><br>
    <li class="active"><a href="#all" data-toggle="tab">All</a></li>
    <li><a href="#closed" data-toggle="tab">Closed</a></li>

  </ul>

  <div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active in" id="all">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th class='text-center'>Last Update</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @all_pos.each do |pos| %>
          <tr class='vcenter'>
            <td><%= pos.name %></td>
            <td><%= pos.description %></td>
            <td class='text-center'><%= pos.updated_at.strftime('%x') %></td>
            <td class='text-right'><button type="button" class="btn btn-item btn-info" data-toggle="modal" data-target="#edit-pos-<%= pos.id %>" id='edit_POS'>Edit</button></td>
            <%= render partial: 'users/edit_pos_modal', locals: {pos: pos} %>
            <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, po_path(pos), method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render partial: 'users/new_pos_modal' %>
</div>